[loggers]
keys=root,demologger

[handlers]
keys=fileHandler

[formatters]
keys=sampleFormatter

[logger_root]
level=ERROR
handlers=fileHandler

[logger_demologger]
level=ERROR
handlers=fileHandler

qualname=demoLogger

[handler_fileHandler]
class=FileHandler
level=ERROR

formatter=sampleFormatter
args=('test2.log', 'w')

[formatter_sampleFormatter]
format=%(asctime)s:%(name)s:%(levelname)s:%(message)s
datefmt=%d/%m/%Y %I:%M:%S %p
